test_python:
  # Use the same image as our Dockerfile
  image: python:slim

  # These two settigns let us cache pip-installed packages
  # It came from the default template
  variables:
    # Put pip-cache in home folder so we can use gitlab cache
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    # Make Firefox run headless.
    MOZ_HEADLESS: "1"
  cache:
    paths:
      - .cache/pip

  # "setUp" phase, before the main build
  before_script:
    - python --version ; pip --version  # For debugging
    - pip install virtualenv
    - virtualenv .venv
    - source .venv/bin/activate

  # This is the main build
  script:
    - pip install -r requirements.txt
    # unit tests
    - python src/manage.py test lists accounts
    # if those pass all test, include functional
    - apt update -y && apt install -y firefox-esr
    - pip install selenium
    - cd src && python manage.py test

  artifacts:
    when: always
    paths:
      - src/functional_tests/screendumps/

test_js:
  image: node:slim
  script:
    - apt update -y && apt install -y firefox-esr
    - cd src/lists/static
    - npm install
    - npx jasmine-browser-runner runSpecs --config=tests/jasmine-browser-runner.config.mjs