# Generated by Django 5.1.6 on 2025-02-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0005_alter_item_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("id",)},
        ),
    ]
